
export enum RoutesApp {
    root = '',
    auth = 'auth',
    logIn = 'log-in',
    signUp = 'sign-up',
    words = 'words',
    addWord = 'add-word',
    testWords = 'test-words',
    phrasalVerbs = 'phrasal-verbs',
    addPhrasalVerb = 'add-phrasal-verb',
    testPhrasalVerbs = 'test-phrasal-verbs',
    idioms = 'idioms',
    addIdiom = 'add-idiom',
    elementsToPractice = 'elementsToPractice',
    // addElementToPractice = 'add-element-to-practice',
    addElementToPractice = 'add-element-to-practice',
    expressions = 'expressions',
    addExpression = 'add-expression',
    grammar = 'grammar',
    practiceLists = 'practice-lists',
    addPracticeList = 'add-practice-list',
    testPracticeLists = 'test-practice-lists',
    test = 'test',
    other = '**'
}
